= WildFly Testing Tools

Various testing tools, utilities and JUnit extensions for testing with a WildFly based server.

== Documentation

For complete documentation, see https://wildfly-extras.github.io/wildfly-testing-tools

== Quick Start

To use the tooling you can simply import the Bill of Materials POM:

[source,xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.wildfly.testing</groupId>
            <artifactId>wildfly-testing-tools-bom</artifactId>
            <version>${version.org.wildfly.testing}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

== Modules

=== JUnit API

The JUnit API contains annotations for skipping tests if minimal module requirements are not met. It also supports
injecting the value of the JBoss Home directory. This can be used with JUnit 6+ and the WildFly JUnit Extension
or WildFly Arquillian.

[source,xml]
----
<dependency>
    <groupId>org.wildfly.testing</groupId>
    <artifactId>wildfly-junit-api</artifactId>
</dependency>
----

=== JUnit Extension

This JUnit Extension manages the lifecycle of a WildFly based server. It starts a server and keeps it running until all
tests have completed.

You can optionally deploy test applications per-test to the server. Only one deployment can be defined per-test.

[source,xml]
----
<dependency>
    <groupId>org.wildfly.testing</groupId>
    <artifactId>wildfly-junit-extension</artifactId>
</dependency>
----

=== Testing Tools

The testing tools can be used to help create deployment descriptors or simple utilities for creating deployments. It
can also create modules and delete created modules.

This can be used for any ShrinkWrap based testing.

[source,xml]
----
<dependency>
    <groupId>org.wildfly.testing</groupId>
    <artifactId>wildfly-testing-tools</artifactId>
</dependency>
----

== Releasing

Releasing the project requires permission to deploy to Maven Central see https://central.sonatype.org/publish/requirements/[Maven Central Release Requirements].
Once everything is setup, you simply need to run the `./release.sh` script. There are two required parameters:

1. `-r` or `--release` which is the version you want to release
2. `-d` or `--development` which is the next development version.

By default the release version cannot contain `SNAPSHOT` and the development version, must container `SNAPSHOT`.

[source,bash]
.Example Command
----
./release -r 1.0.0.Final -d 1.0.1.Final-SNAPSHOT
----

=== Supported Arguments

|===
|Argument | Requires Value | Description

| `-d`, `--development`
| Yes
| The next version for the development cycle.

| `-f`, `--force`
| No
| Forces to allow a SNAPSHOT suffix in release version and not require one for the development version.

| `-h`, `--help`
| N/A
| Displays this help

| `--notes-start-tag`
| Unused
| Passes the `--notes-from-tag` and the argument to the `gh create release` command.

| `-p`, `--prerelease`
| Unused
| Passes the `--prerelease` to the `gh create release` command.

| `-r`, `--release`
| Yes
| The version to be released. Also used for the tag.

| `--dry-run`
| No
| Executes the release in as a dry-run. Nothing will be updated or pushed.

| `--no-push`
| No
| Executes the release in, but doesn't actually push the changes to GitHub or publish the release on Maven Central.
Any next steps should you want to continue the release will need to be manual.

| `-v`, `--verbose`
| No
| Prints verbose output.

|===


Any additional arguments are considered arguments for the Maven command.

