# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: WildFly Testing Tools WildFly Integration - CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/wildfly-ci.yml'
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  MVN_CMD: './mvnw -V -B'

jobs:

  wildfly-test-and-build:
    name: 'wildfly-test-${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' , 'windows-latest' ]

    steps:
      - uses: actions/checkout@v6
      - uses: wildfly-extras/wildfly-nightly-download@v1
        id: wildfly-nightly
      - name: Set up JDKs
        uses: actions/setup-java@v5
        with:
          cache: 'maven'
          distribution: 'temurin'
          java-version: |
            17
            21
            26-ea
            25
      - name: Build and Test on ${{ matrix.os }} - 25 with WildFly ${{steps.wildfly-nightly.outputs.wildfly-version}}
        run: ${{ env.MVN_CMD }} clean verify '-Dversion.org.wildfly=${{steps.wildfly-nightly.outputs.wildfly-version}}'
      - name: Build and Test on ${{ matrix.os }} - 26 with WildFly ${{steps.wildfly-nightly.outputs.wildfly-version}}
        run: ${{ env.MVN_CMD }} verify '-Dversion.org.wildfly=${{steps.wildfly-nightly.outputs.wildfly-version}}' '-Dtest.java.home=${{env.JAVA_HOME_26_X64}}${{env.JAVA_HOME_26_ARM64}}' '-Dsurefire.reportsDirectory=target/surefire-reports-java26' '-Dfailsafe.reportsDirectory=target/failsafe-reports-java26'
      - name: Build and Test on ${{ matrix.os }} - 21 with WildFly ${{steps.wildfly-nightly.outputs.wildfly-version}}
        run: ${{ env.MVN_CMD }} verify '-Dversion.org.wildfly=${{steps.wildfly-nightly.outputs.wildfly-version}}' '-Dtest.java.home=${{env.JAVA_HOME_21_X64}}${{env.JAVA_HOME_21_ARM64}}' '-Dsurefire.reportsDirectory=target/surefire-reports-java21' '-Dfailsafe.reportsDirectory=target/failsafe-reports-java21'
      - name: Build and Test on ${{ matrix.os }} - 17 with WildFly ${{steps.wildfly-nightly.outputs.wildfly-version}}
        run: ${{ env.MVN_CMD }} verify '-Dversion.org.wildfly=${{steps.wildfly-nightly.outputs.wildfly-version}}' '-Dtest.java.home=${{env.JAVA_HOME_17_X64}}${{env.JAVA_HOME_17_ARM64}}' '-Dsurefire.reportsDirectory=target/surefire-reports-java17' '-Dfailsafe.reportsDirectory=target/failsafe-reports-java17'
      - name: Upload test logs for failed run
        uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: test-reports-${{ matrix.os }}
          path: |
            **/*.log
            **/surefire-reports*/**
            **/failsafe-reports*/**